### ISSUE TITLE
buy_market市价买单不传amount, 是全仓买入吗？ 如何理解？

### ISSUE THREAD

**Issue by AlbertChanX** [merz9b/okex_restful_api#1]
谢谢！

**Comment by merz9b** [comment]
@githubcyc 
这里是参考官方文档写的:
https://github.com/okcoin-okex/API-docs-OKEx.com/blob/master/API-For-Spot-CN/%E5%B8%81%E5%B8%81%E4%BA%A4%E6%98%93REST%20API.md

市价买单不传amount, 但需要传price, 即根据市价一共买入指定price数量。
